apiVersion: apps/v1
kind: Deployment
metadata:
  name: aide-fl-minio
spec:
  selector:
    matchLabels:
      run: aide-fl-minio
  replicas: 1
  template:
    metadata:
      labels:
        run: aide-fl-minio
    spec:
      containers:
      - name: aide-fl-minio
        image: minio/minio
        args: ["server", "/data", "--console-address", ":9001"]
        ports:
        - containerPort: 9000  # API
        - containerPort: 9001  # Console
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: aide-fl-minio-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: aide-fl-minio
spec:
  ports:
  - port: 9000
    targetPort: 9000
    name: api
  - port: 9001
    targetPort: 9001
    name: console
  selector:
    run: aide-fl-minio