apiVersion: v1
kind: Service
metadata:
  name: aide-fl-server
  labels:
    run: aide-fl-server
spec:
  clusterIP: 10.96.0.21
  ports:
  - name: fl-grpc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: aide-fl-server
  type: ClusterIP
