apiVersion: apps/v1
kind: Deployment
metadata:
  name: aide-fl-client-nf2
  labels:
    app.kubernetes.io/name: aide-fl-client
    app.kubernetes.io/instance: aide-fl-client-nf2
spec:
  selector:
    matchLabels:
      run: aide-fl-client-nf2
  replicas: 1
  template:
    metadata:
      labels:
        run: aide-fl-client-nf2
    spec:
      containers:
      - name: aide-client
        image: gitlab.ilabt.imec.be:4567/aide-fl/aide-infra/cnl-client
        args: ["--cid", "2", "--experiment", "APFed", "--server", "10.96.0.21:8080"]
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: aide-containerregistry